### ISSUE TITLE
Configurar Pipeline de Deploy 

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#108]
## Descrição

Automatizar o processo atual de CD pelo GIthub Actions.

## Task
- [ ] Conectar via SSH com a VM na Azure.
- [x] Guardar secrets no Github.
- [x] Configurar script para buildar ambiente na VM.

## Critérios de Aceitação
- [ ] Devem existir 2 ambientes de deploy: DEV e QAS (ao final do projeto PROD)
- [x] Os processos devem ser acionados quando aconteer um PR entre as branches: dev e qas.
- [x] O script shell implatado na VM deve ser capaz de atualizar a versão do código na máquina e buildar corretamente a versão do projeto.   
- [x] Os ambientes de DEV e QAS devem compartilhar o mesmo banco de dados.
