### ISSUE TITLE
US11 - Gerenciar Pontos de Partida

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2024.1-CALCULUS-DOC#144]
### História
**Alberto** deseja **criar ponto de partidas** de aprendizado,
Para **organizar as jornadas** dentro dessa plataforma educacional.

### Tasks

 - [x] Criar protótipo de alta fidelidade.
 - [x] Implementar CRUD de livro.
 - [x] Criar a interface para criação de livros, seguindo o protótipo.
 - [x] Implementar a funcionalidade de adicionar e organizar jornadas de um livro.
 - [x] Permitir a visualização e edição dos livros criados.

### Critérios de Aceitação

 - [x] Deve ser possível acessar uma lista de jornadas relacionados ao ponto de partida.
 - [x] Deve ser possível ordenar os pontos de partida.
 - [x] Um ponto de partida possui várias jornadas, e uma jornada está em apenas um ponto de partida.
 - [x] Somente o usuário com role de admin podem deletar ponto de partidas de todos os usuários.
 - [x] Os usuários com role de admin e professor poderá criar/editar/deletar ponto de partidas criados por ele mesmo.
 - [x] Somente o admin deve poder ordenar os pontos de partida.
### 
![Pontos-de-ordenação](https://github.com/user-attachments/assets/a4328f37-b12d-4684-a136-18e3b512408c)
