### ISSUE TITLE
US01 - Criar Conta

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#69]
### História
Pedro, como um **novo usuário**,
Gostaria de **criar uma conta**,
Para  **utilizar a aplicação** para estudar Calculo.

### Tasks
 - [x] Criar um protótipo de alta fidelidade.
 - [x] Criar um formulário de cadastro com campos obrigatórios (nome, username, e-mail, senha), seguindo o protótipo.
 - [x] Implementar validação de dados no formulário de cadastro.
 - [x] Implementar envio de e-mail de validação de conta para o usuário.

### Critérios de Aceitação

- [ ] O usuário deve conseguir se cadastrar com a conta da Google , Microsoft e Apple.
- [ ] O usuário caso queira cadastrar com o email, aparecer os inputs de nome, username e senha para ele pode concluir seu cadastro.
- [ ] Para efetuar preenchimento do cadastro, os seguintes campos são obrigatorios de Email, Senha e Username e name.
- [ ] Os campos Email, Username devem ser unicos
- [ ] Após preencher fomulário deve ser enviado um email para o email cadastrado no formulário.
- [ ] Após cadastro e ativação da conta redirecionar para tela de login.

###
![Cadastro](https://github.com/user-attachments/assets/2fc8f8cf-ea13-472b-acb2-57fffa44363c)
![Cadastro 2](https://i.ibb.co/qmHfVmn/register-verification.png)
![Cadastro  3](https://github.com/user-attachments/assets/7668a936-5e50-4d32-83ef-430c945904b5)
