### ISSUE TITLE
US02 - Login

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#70]
### História
Valentina, uma **usuária** da plataforma,
Gostaria de **fazer login**,
Para entrar na sua conta e  **usar a aplicação** para aprender.

### Tasks
 - [x] Criar protótipo de alta fidelidade. 
 - [x] Criar a interface da tela de login seguindo o protótipo.
 - [x] Implementar a validação de entrada de dados no frontend.
 - [x] Exibir mensagens de erro para entradas inválidas ou falhas de autenticação.
 - [x] Configurar a comunicação com o backend para autenticação do usuário.
 - [x] Criar endpoints de autenticação no backend.
 - [x] Implementar lógica de autenticação no backend, incluindo verificação de credenciais e geração de tokens JWT.

### Critérios de Aceitação

 - [ ] O usuário poderá entrar com as contas Google e da Microsoft e da Apple.
 - [ ] Se as credenciais estiverem corretas, o usuário deve ser autenticado e redirecionado para a tela de Home.
 - [ ] Se as credenciais estiverem incorretas, deve apresentar que ou senha esta incorreta ou não foi possível encontrar email relacionado.
 - [ ] Se as credenciais não existirem na base de dados, deve ser apresentado uma mensagem dizendo que conta nao existe na base e ofertar cadastro ao usuário.
 - [ ] Se usuário tente logar com um conta não ativada, deve ser apresentado mensagem dizendo que conta precisa ser validada

### Protótipo. 

![Login](https://github.com/user-attachments/assets/445695ea-6e67-48a5-a1d2-f98f34a18228)
