### ISSUE TITLE
US03 - Gerenciar Roles

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#71]
### História
Professor Roberto, na figura de **administrador**,
Gostaria que fosse possível **atribuir a role de administrador** ao Professor Alberto,
Para que o mesmo possa **criar conteúdo para seus alunos** e também **gerenciar as permissões de novos professores** que ingressarem na plataforma.

### Tasks
- [x] Criar protótipo de alta fidelidade .
- [x] Criar a interface da tela de login seguindo o protótipo.
- [x] Implementar a funcionalidade de atribuir a role de Professor.
- [x] Definir permissões específicas para a role de Professor.
- [x] Implementar a funcionalidade de atribuir a role de Admin.
- [x] Definir permissões específicas para a role de Admin.

### Critérios de Aceitação

- [ ] Deve ser possível atribuir a role de Professor a um usuário.
- [ ] Deve ser possível atribuir a role de Admin a um usuário.
- [ ] Um usuário Admin deve poder criar e gerenciar conteúdos, além de poder atribuir papéis a outros usuários.
- [ ] Usuários com a role de Admin devem ter acesso total conforme definido.

### Protótipo.
![Admin Panel 2](https://github.com/user-attachments/assets/d19276ce-df7a-4706-bba7-d67d70a7c4fa)
![Admin Panel 3](https://github.com/user-attachments/assets/78a6b79a-754e-4da8-b48e-33119cb905ba)
