### ISSUE TITLE
US04 - Recuperar Conta 

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#72]
### História
Valentina **esqueceu sua senha**,
E gostaria de **redefinir a senha**,
Para **recuperar acesso a sua conta**.

### Tasks
 - [x] Criar os protótipos de alta fidelidade para este fluxo.
 - [x] Criar as interfaces de recuperação de conta seguindo o protótipo validado.
 - [x] Implementar a funcionalidade para enviar um e-mail de recuperação.
 - [x] Criar a página de redefinição de senha acessada pelo link no e-mail.
 - [x] Implementar a validação e atualização a nova senha no sistema.

### Critérios de Aceitação
- [ ] Deve ser possível inserir o e-mail na interface para solicitar recuperação de conta.
- [ ] O sistema deve enviar um e-mail de recuperação com um link para redefinição de senha ao usuário.
- [ ] A página de redefinição de senha deve ser acessível apenas através do link no e-mail de recuperação.
- [ ] A nova senha deve ser validada e atualizada no sistema com sucesso, seguindo os padrões de criação de senha.
- [ ] Em caso de tentativa de recuperar uma conta não registrada, a interface deve acusar um erro.
- [ ] A interface de redefinição de senha só deve aceitar a estrutura de um e-mail como input   

### Protótipo
![recuperar senha 1](https://github.com/user-attachments/assets/3c82b838-2dd7-4290-9314-4999b826c3a4)
![recuperar senha 2](https://i.ibb.co/YPqXM0j/email-register.png)
![Recuperar senha 3](https://github.com/user-attachments/assets/927adf56-aed0-4685-991b-ef09b0871186)
