### ISSUE TITLE
US05 - Estúdio de Criação 

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#74]
### História
Alberto **um professor**,
Quer **escrever e formatar conteúdo** usando **Markdown e LaTeX** no estúdio,
Para poder **criar materiais de aula** ricos em texto **formatado e com fórmulas matemáticas**

### Tasks
- [x]  Criar protótipo de alta fidelidade para esse fluxo.
- [x] Criar microsserviço JourneyService e EndPoints de CRUD necessários.
- [x] Criar coleção no Banco de Dados do novo serviço para salvar conteúdos.
- [x] Implementar a funcionalidade de escrita em Markdown no estúdio.
- [x] Criar uma interface de edição com pré-visualização do conteúdo.
- [x] Configurar renderização da página Markdown na aplicação web.

### Critérios de Aceitação
- [ ] A funcionalidade de escrita em Markdown deve estar implementada e permitir a inserção de texto formatado.
- [ ] A interface de edição deve oferecer uma pré-visualização em tempo real do conteúdo Markdown e LaTeX.
- [ ] O conteúdo Markdown e LaTeX deve ser corretamente renderizado na aplicação web, exibindo texto formatado e fórmulas matemáticas de acordo com as especificações.
- [ ] A funcionalidade deve aceitar adição de figuras, imagens dinamicas, gifs, etc.
- [ ] Deve ser possível criar, editar e exlcuir conteúdos.

![Estudio-de-Criacao-de-Texto](https://github.com/user-attachments/assets/46e42099-5764-4d20-bfe8-e616f78d318a)

![Estudio-de-Criacao-Lateral-Maximizada](https://github.com/user-attachments/assets/27614b6d-ca9c-4060-b80e-76c288b63c2e)

![Estudio-de-Criacao-Excluir](https://github.com/user-attachments/assets/60610c54-4700-4f5f-906b-ba729347cc76)
