### ISSUE TITLE
US06 - Gerenciar Jornada

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#75]
### História
Alberto um **professor**,
Quer **criar jornadas de aprendizado**,
Para poder **organizar as trilhas** educacional de forma estruturada e sequencial

### Tasks
 - [ ] Criar protótipo de alta fidelidade deste fluxo.
 - [ ] Implementar CRUD de jornada.
 - [ ] Criar a interface para criação de jornadas, seguindo o protótipo.
 - [ ] Implementar a funcionalidade de adicionar e organizar trilhas dentro das jornadas.
 - [ ] Permitir a visualização e edição das jornadas criadas.

### Critérios de Aceitação

 - [ ] Deve ser possível acessar uma lista de trilhas relacionados a Jornada.
 - [ ] Uma Jornada possui varias trilhas, e uma trilha apenas uma Jornada.
 - [ ] Os usuário com role de admin podem deletar jornadas de todos os usuários.
 - [ ] Os usuários com role de admin e professor poderá criar/editar/deletar apenas jornadas criadas por ele mesmo. 

![Minhas-Jornadas](https://github.com/user-attachments/assets/8f8ba065-8308-4885-a351-e7ac66040a88)

![Minhas-Jornadas-EditarJornada](https://github.com/user-attachments/assets/00eee313-d687-402a-b9d7-fa5ac206231a)

![Minhas-Jornadas-Excluir](https://github.com/user-attachments/assets/8f34ef80-10b7-445a-a1ee-0058edf38111)
