### ISSUE TITLE
US07 - Gerenciar Trilha

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#76]
### História
**Alberto** deseja **criar trilhas** de aprendizado,
Para **organizar os conteúdos** de uma jornada educacional.

### Tasks

 - [ ] Criar protótipo de alta fidelidade.
 - [ ] Implementar CRUD de trilha.
 - [ ] Criar a interface para criação de trilhas, seguindo o protótipo.
 - [ ] Implementar a funcionalidade de adicionar e organizar conteúdos dentro de uma trilha.
 - [ ] Permitir a visualização e edição das trilhas criadas.

### Critérios de Aceitação

 - [ ] Deve ser possível acessar uma lista de conteúdos relacionados a trilha.
 - [ ] Uma trilha possui varios conteúdos, e um contéudo está em apenas uma trilha.
 - [ ] Somente os usuário com role de admin podem deletar trilhas de todos os usuários.
 - [ ] Os usuários com role de admin e professor poderá criar/editar/deletar trilhas criadas por ele mesmo.

![Minhas-Jornadas-Trilha-Professor](https://github.com/user-attachments/assets/1a84edcc-35ca-4088-a30d-f54530c989b5)

![Minhas-Jornadas-Criar-Trilha](https://github.com/user-attachments/assets/f69b6737-3220-4e04-9551-1cbd239693d0)

![Minhas-Jornadas-Excluir-Trilha](https://github.com/user-attachments/assets/045e631e-79b9-4637-8b3f-a80b2d5ff6ee)
