### ISSUE TITLE
US08 - Visualização de Trilhas

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#78]
### História
Como um **aluno**,
Eu quero **visualizar as trilhas** de uma jornada de aprendizado,
Para **ver o caminho** a ser seguido sequencialmente em uma jornada.

### Tasks
- [x] Criar o protótipo de alta fidelidade.
- [x] Criar card com informações de jornada.
- [x] Criar visualização gráfica das trilhas da jornada

### Critérios de Aceitação

 - [x] Visualizar card com informações da jornada selecionada
- [x] Deve ser possível visualizar a quantidade de trilhas no card.
- [x] O progresso do aluno na jornada deve ser mostrada no card.
- [x] A contabilização de progresso começa apenas quando o usuário acessa o conteúdo de uma trilha.
- [x] Ao completar uma trilha ela deve ser pintada de verde para mostrar o progresso.
 - [x] Visualizar grafo com as trilhas que compõem a jornada
 - [x] O aluno conseguirá acessar as jornadas seguintes quando clicar na seta de avançar.
 - [x] O aluno conseguirá acessar as jornadas anteriores quando clicar na seta de voltar.

 
### Prototipação

![Trilha](https://github.com/user-attachments/assets/cee9146c-4966-4ad1-8d4c-7f3026c79a1a)
