### ISSUE TITLE
US09 - Visualizar HomePage

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#79]
### História
Como um **aluno**,
Eu quero **visualizar a HomePage** da plataforma,
Para **visualizar minhas jornadas** em andamento **e buscar por pontos de partida** na plataforma.

### Tasks
- [x] Criar protótipo de alta fidelidade. 
- [x] Criar a interface para exibição das jornadas, seguindo o protótipo.
- [x] Implementar a funcionalidade de ingresso em uma jornada.
- [x] Implementar notificação sobre o ingresso bem-sucedido na jornada.
- [x] Implementar notificação quando há atualização na jornada.

### Critérios de Aceitação

- [x] Ao acessar um conteúdo de uma trilha, essa jornada deverá ser adicionada na parte de "Jornadas em andamento".
- [x] Deve ser possível pesquisar os pontos de partida da plataforma pelo título ou descrição.
- [x] Ao clicar na seta ao lado da descrição do ponto de partida deverá abrir uma secção de jornadas pertencentes a esse ponto de partida. 
- [x] Essa secção deverá estar ordenada conforme definido pelo admin.

### Prototipação

![HomeBook](https://github.com/user-attachments/assets/14fbd7d2-df61-4a71-9b89-904863dacacd)
