### ISSUE TITLE
US10 - Visualizar Contéudo

### ISSUE THREAD

**Issue by paulohgontijoo** [fga-eps-mds/2024.1-CALCULUS-DOC#80]
### História
Vanessa uma  **aluna**,
Eu quero poder **acessar conteúdo** de forma interativa e dinâmica,
Para **ter uma melhor** experiência de aprendizado

### Tasks
 - [x] Criar protótipo de alta fidelidade.
 - [x] Criar a interface para exibição do passo-a-passo dos conteúdos, seguindo o protótipo.

### Critérios de Aceitação
- [x] o sistema deve exibir os conteúdos da trilha para que o aluno possa consumir. 
- [x] Deve ser possível para o aluno navegar entre os contéudos dos exercícios intuitivamente acessados anteriormente.
- [x] O aluno somente conseguirá acessar os próximos contéudos quando clicar no botão "Próximo contéudo".
- [x] Botão de próximo conteúdo deve ser apresentando apenas quando o aluno chegar ao final do conteúdo atual.
- [x] No menu lateral do canto esquerdo o aluno não poderá acessar contéudos que ainda não foram acessados anteriormente.
- [x] Botão de acessar contéudo anterior deve ser apresentado a partir do segundo conteúdo de uma trilha, caso não haja, o botão deve redirecionar para o conteúdo da trilha anterior, se houver.
- [x] Ao chegar ao fim de uma trilha, o botão deve redirecionar o aluno ao conteúdo da próxima trilha, caso haja. 

### Protótipo
![image](https://i.postimg.cc/MKZd0nNk/boaaaaa.png)
